alias dch='docker-cloud -h'
alias dcv='docker-cloud -v'

alias dca='docker-cloud action'
alias dcc='docker-cloud container'
alias dcev='docker-cloud event'
alias dce='docker-cloud exec'
alias dcl='docker-cloud login'
alias dcn='docker-cloud node'
alias dcnc='docker-cloud nodecluster'
alias dcre='docker-cloud repository'
alias dcr='docker-cloud run'
alias dcs='docker-cloud service'
alias dcst='docker-cloud stack'
alias dct='docker-cloud tag'
alias dctr='docker-cloud trigger'
alias dcu='docker-cloud up'
